// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addtag.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addTag = `-- name: AddTag :one
INSERT INTO tags (id, created_at, updated_at, name)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
RETURNING id, created_at, updated_at, name
`

type AddTagParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) AddTag(ctx context.Context, arg AddTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, addTag,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
