// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deletequotetags.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteQuoteTags = `-- name: DeleteQuoteTags :exec
DELETE FROM quotes_tags_link
WHERE quote_id=?1
`

func (q *Queries) DeleteQuoteTags(ctx context.Context, quoteID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuoteTags, quoteID)
	return err
}
