// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editquote.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const editQuote = `-- name: EditQuote :one
SELECT id, created_at, updated_at, quote, author, last_served_at
FROM quotes
WHERE id=?1
`

func (q *Queries) EditQuote(ctx context.Context, id uuid.UUID) (Quote, error) {
	row := q.db.QueryRowContext(ctx, editQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quote,
		&i.Author,
		&i.LastServedAt,
	)
	return i, err
}
