// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: puteditedquote.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const putEditedQuote = `-- name: PutEditedQuote :one
UPDATE quotes
SET
    updated_at = ?4,
    quote = ?2,
    author = ?3
WHERE id = ?1
RETURNING id, created_at, updated_at, quote, author, last_served_at
`

type PutEditedQuoteParams struct {
	ID        uuid.UUID
	Quote     string
	Author    sql.NullString
	UpdatedAt time.Time
}

func (q *Queries) PutEditedQuote(ctx context.Context, arg PutEditedQuoteParams) (Quote, error) {
	row := q.db.QueryRowContext(ctx, putEditedQuote,
		arg.ID,
		arg.Quote,
		arg.Author,
		arg.UpdatedAt,
	)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Quote,
		&i.Author,
		&i.LastServedAt,
	)
	return i, err
}
