// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotesreset.sql

package database

import (
	"context"
)

const quotesReset = `-- name: QuotesReset :exec
DELETE
FROM quotes
`

func (q *Queries) QuotesReset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, quotesReset)
	return err
}
