// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setquotetags.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setQuoteTags = `-- name: SetQuoteTags :exec
INSERT INTO quotes_tags_link (quote_id, tag_id)
VALUES (
    ?1,
    ?2
)
`

type SetQuoteTagsParams struct {
	QuoteID uuid.UUID
	TagID   uuid.UUID
}

func (q *Queries) SetQuoteTags(ctx context.Context, arg SetQuoteTagsParams) error {
	_, err := q.db.ExecContext(ctx, setQuoteTags, arg.QuoteID, arg.TagID)
	return err
}
